server:
  port: 8080
  debugging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

spring:
#  main:
#    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: simple
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: company
          uri: http://localhost:8082
          predicates:
            - Path=/companies
#          filters:
#            - UserAuthFilter