server:
  port: 8081
  debugging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG
spring:
#  main:
#    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: simple
          uri: https://httpbin.org/get
          predicates:
            - Path=/get/**
        - id: api
          uri: http://localhost:8080/api/
          predicates:
            - Path=/api/**
            - filter:
                - GlobalFilter