spring:
  #  main:
  #    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: simple
          uri: http://authentication:8081
          predicates:
            - Path=/users/**
        - id: company
          uri: http://reservation:8082
          predicates:
            - Path=/companies/**
        - id: reservation
          uri: http://reservation:8082
          predicates:
            - Path=/reservations/**
            - Method=POST
          filters:
            UserAuthFilter
        - id: reservationAdmin
          uri: http://reservation:8082
          predicates:
            - Path=/reservations/**
            - Method=GET
          filters:
            AdminAuthFilter
        - id: resourcesAdmin
          uri: http://reservation:8082
          predicates:
            - Path=/resources/**
            - Method=POST
          filters:
            AdminAuthFilter
        - id: resourcesUser
          uri: http://reservation:8082
          predicates:
            - Path=/resources/**
            - Method=GET
          filters:
            UserAuthFilter
        - id: tagsAdmin
          uri: http://reservation:8082
          predicates:
            - Path=/tags/**
            - Method=POST,DELETE
          filters:
            AdminAuthFilter
        - id: tagsUser
          uri: http://reservation:8082
          predicates:
            - Path=/tags/**
            - Method=GET
          filters:
            UserAuthFilter
        - id: reportUser
          uri: http://reservation:8082
          predicates:
            - Path=/reports/**
            - Method=POST
          filters:
            UserAuthFilter
        - id: reportAdmin
          uri: http://reservation:8082
          predicates:
            - Path=/reports/**
            - Method=GET
          filters:
            AdminAuthFilter
