server:
  port: 8080
  debugging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

spring:
#  main:
#    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: simple
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: company
          uri: http://localhost:8082
          predicates:
            - Path=/companies/**
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/**
            - Method=POST
          filters:
            UserAuthFilter
        - id: reservationAdmin
          uri: http://localhost:8082
          predicates:
              - Path=/reservations/**
              - Method=GET
          filters:
            AdminAuthFilter
        - id: resourcesAdmin
          uri: http://localhost:8082
          predicates:
            - Path=/resources/**
            - Method=POST
          filters:
            AdminAuthFilter
        - id: resourcesUser
          uri: http://localhost:8082
          predicates:
            - Path=/resources/**
            - Method=GET
          filters:
            UserAuthFilter
        - id: tagsAdmin
          uri: http://localhost:8082
          predicates:
            - Path=/tags/**
            - Method=POST,DELETE
          filters:
            AdminAuthFilter
        - id: tagsUser
          uri: http://localhost:8082
          predicates:
            - Path=/tags/**
            - Method=GET
          filters:
            UserAuthFilter
        - id: reportUser
          uri: http://localhost:8082
          predicates:
            - Path=/reports/**
            - Method=POST
          filters:
            UserAuthFilter
        - id: reportAdmin
          uri: http://localhost:8082
          predicates:
            - Path=/reports/**
            - Method=GET
          filters:
            AdminAuthFilter
