spring:
  #  main:
  #    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: simple
          uri: http://authentication:8081
          predicates:
            - Path=/users/**
        - id: company
          uri: http://reservation:8082
          predicates:
            - Path=/companies
        - id: reservation
          uri: http://reservation:8082
          predicates:
            - Path=/reservations
          filters:
            UserAuthFilter
        - id: resources
          uri: http://reservation:8082
          predicates:
            - Path=/resources/**